#!/bin/sh

set -e

test $DEBIAN_SCRIPT_DEBUG && set -v -x

export PATH=/var/lib/gems/1.9.1/bin:$PATH

case "$1" in
    configure)
        # Make sure bundler is installed
        BUNDLER_VERSION=1.0.0
        if ! gem list bundler | grep -q $BUNDLER_VERSION
        then
            gem install bundler --version $BUNDLER_VERSION
        fi
        cd /srv/vqdata/production/docroot
        bundle install --quiet

        # Check we installed everything successfully
        bundle check
    ;;

    reconfigure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

